name: pi-bluetooth
version: '1.0'
summary: Setup Bluetooth on Raspberry Pi running Ubuntu Core
description: |
  Confined snap meant to enable bluetooth on RPi devices on Ubuntu Core systems
grade: stable
confinement: strict
base: core18
architectures:
  - build-on: armhf
  - build-on: arm64

apps:
  btuart:
    command: btuart
    daemon: simple
    plugs:
      - serial-port
      - hardware-observe
  bthelper:
    command: bthelper
    plugs:
      - serial-port
      - hardware-observe
  hciattach:
    command: hciattach
    plugs:
      - serial-port
      - hardware-observe
  btattach:
    command: btattach
    plugs:
      - serial-port
      - hardware-observe

parts:
  file-dump:
    plugin: dump
    source: dump
  bluez:
    plugin: nil
    stage-snaps: 
      - bluez
    prime:
      - usr/bin/hciconfig
      - usr/bin/hcidump
      - usr/bin/hciattach
      - usr/bin/btattach
      - usr/bin/hcitool
      - usr/bin/sdptool
