#! /bin/sh

# serial-port is connected, now we can start the btuart and bthelper services
if snapctl services ${SNAP_NAME}.btuart | grep -q inactive; then
  snapctl start --enable ${SNAP_NAME}.btuart 2>&1 || true
fi
if snapctl services ${SNAP_NAME}.bthelper| grep -q inactive; then
  snapctl start --enable ${SNAP_NAME}.bthelper 2>&1 || true
fi
